export const HELP_LINES = Object.freeze([
  'Backend Team Harness',
  '',
  'Usage:',
  '  bth init [path] [--force] [--allow-unversioned]',
  '  bth doctor [path] [--json]',
  '  bth intelligence inspect [path] [--no-cache] [--json]',
  '  bth intelligence warm-cache [path] [--json]',
  '  bth work <requirement> [path] [--id <id>] [--by <actor>] [--decisions <json>] [--approve] [--run --allow-write] [--acknowledge-network-risk] [--json]',
  '  bth config migrate [path] --allow-write [--json]',
  '  bth check [path] [--acknowledge-network-risk] [--json]',
  '  bth pack list [--json]',
  '  bth pack install <id> [path] [--json]',
  '  bth baseline update [path] [--json]',
  '  bth task create <id> [path] [--title <text>] [--context <text>] [--by <actor>] [--json]',
  '  bth task context <id> [path] --text <text> --by <actor> [--json]',
  '  bth task plan <id> [path] --text <text> --by <actor> [--json]',
  '  bth task status <id> [path] [--json]',
  '  bth task handoff <id> [path] --from <actor> --to <actor> --reason <text> [--json]',
  '  bth task export-plan <id> [path] [--context-budget <characters>] [--json]',
  '  bth task advance <id> <state> [path] --by <actor> [--approve] [--reason <text>] [--json]',
  '  bth interview start <id> [path] --requirement <text> --by <actor> [--title <text>] [--json]',
  '  bth interview answer <id> [path] --question <id> --text <text> --by <actor> [--status <answered|unknown|conflict>] [--claims <json>] [--json]',
  '  bth interview revise <id> [path] --question <id> --text <text> --by <actor> [--status <answered|unknown|conflict>] [--claims <json>] [--json]',
  '  bth interview resolve <id> [path] --candidate <id> --reason <text> --by <actor> [--json]',
  '  bth interview rebind <id> [path] --by <actor> [--json]',
  '  bth interview status <id> [path] [--json]',
  '  bth interview finalize <id> [path] --by <actor> [--json]',
  '  bth implement configure <codex|claude> [path] [--mode <auto|fast|balanced|deep>] [--allowed-prefixes <json>] [--force] [--json]',
  '  bth implement providers [path] [--json]',
  '  bth implement run <id> [path] --by <actor> --allow-write [--acknowledge-network-risk] [--json]',
  '  bth implement apply <id> [path] --by <actor> --allow-write [--json]',
  '  bth implement status <id> [path] [--json]',
  '  bth implement reset <id> [path] --by <actor> --discard-workspace [--json]',
  '  bth implement cleanup <id> [path] --by <actor> --discard-workspace [--json]',
  '  bth verify <id> [path] [--acknowledge-network-risk] [--json]',
  '  bth diagnose <id> [path] [--json]',
  '  bth version',
  '',
  'Safety:',
  '  init never creates the project directory, rejects symlink paths, and backs up every --force overwrite.',
  '  verify runs only project-contained executables declared in verification.json after an approved task state.',
  '  interview binds requirements, deterministic project facts, and a reviewable plan to one Git source fingerprint.',
  '  implement runs only inside a detached task worktree; apply is a separate explicit, sealed, rollback-capable operation.',
  '  acknowledge-network-risk permits a declared network-capable command; it does not enforce operating-system egress isolation.',
  '  VERIFIED requires fresh structured test reports with at least one executed test.'
])

export function printHelp() {
  console.log(HELP_LINES.join('\n'))
}
